export const Customers = [
  {
    SN: 1,
    CompetencyType: 'Technical',
    Skills: 'Understands internal and external customer requirements, customer needs and organisation’s service standards and takes initiative to provide value-added advice/ suggestions to address needs.',
    Attachment: 'true',
    CurrentRate: '3/5',
    RequiredRate: '3/5',
    Gap: '0',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    PlanNo:'2',
    TotalHours: '10',
    TotalBudget: '$3000',
    Remarks: ' This training has equipped me positively with problem-solving skills. It has helped me to see different ways to think and leverage challenges in my career',
  },
  {
    SN: 2,
    CompetencyType: 'Technical',
    Skills: 'Escalates suggestions on how to provide better services',
    Attachment: 'true',
    CurrentRate: '2/5',
    RequiredRate: '4/5',
    Gap: '-2',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '7',
    TotalBudget: '$1500',
    Remarks:'The new diverse expertise I acquire from the training will surely be pragmatically used',
  },
  {
    SN: 3,
    CompetencyType: 'Technical',
    Skills: 'Builds rapport with internal and external customers and maintains customers’ trust by providing prompt, effective and quality service, takes continued interest in customers’ affairs.',
    Attachment: 'false',
    CurrentRate: '4/5',
    RequiredRate: '1/5',
    Gap: '3',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '8',
    TotalBudget: '$2200',
    Remarks:'',
  },
  {
    SN: 4,
    CompetencyType: 'Developing Self & Others',
    Skills: 'Demonstrates interest in professional development, proactively identifies and surfaces self-development areas and personal development goals that can contribute to current and future job requirements',
    Attachment: 'false',
    CurrentRate: '1/5',
    RequiredRate: '5/5',
    Gap: '-4',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '5',
    TotalBudget: '$4000',
    Remarks:'To stay competitive in today’s job market. Would require developing of new skills',
  },
   {
    SN: 5,
    CompetencyType: 'Technical',
    Skills: 'Understands internal and external customer requirements, customer needs and organisation’s service standards and takes initiative to provide value-added advice/ suggestions to address needs.',
    Attachment: 'true',
    CurrentRate: '3/5',
    RequiredRate: '3/5',
    Gap: '0',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '10',
     TotalBudget: '$3000',
     Remarks:'',
  },
  {
    SN: 6,
    CompetencyType: 'Technical',
    Skills: 'Escalates suggestions on how to provide better services',
    Attachment: 'false',
    CurrentRate: '3/5',
    RequiredRate: '4/5',
    Gap: '-1',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '7',
    TotalBudget: '$1500',
    Remarks:'',
  },
  {
    SN: 7,
    CompetencyType: 'Technical',
    Skills: 'Builds rapport with internal and external customers and maintains customers’ trust by providing prompt, effective and quality service, takes continued interest in customers’ affairs.',
    Attachment: 'false',
    CurrentRate: '3/5',
    RequiredRate: '1/5',
    Gap: '2',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '8',
    TotalBudget: '$2200',
    Remarks:'',
  },
  {
    SN: 8,
    CompetencyType: 'Technical',
    Skills: 'Escalates suggestions on how to provide better services',
    Attachment: 'false',
    CurrentRate: '3/5',
    RequiredRate: '4/5',
    Gap: '-2',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '7',
    TotalBudget: '$1500',
    Remarks:'',
  },
  {
    SN: 9,
    CompetencyType: 'Technical',
    Skills: 'Understands internal and external customer requirements, customer needs and organisation’s service standards and takes initiative to provide value-added advice/ suggestions to address needs.',
    Attachment: 'true',
    CurrentRate: '3/5',
    RequiredRate: '3/5',
    Gap: '0',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '10',
    TotalBudget: '$3000',
    Remarks:'',
  },
  {
    SN: 10,
    CompetencyType: 'Technical',
    Skills: 'Escalates suggestions on how to provide better services',
    Attachment: 'true',
    CurrentRate: '3/5',
    RequiredRate: '4/5',
    Gap: '-1',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '7',
    TotalBudget: '$1500',
    Remarks:'',
  },
  {
    SN: 11,
    CompetencyType: 'Technical',
    Skills: 'Builds rapport with internal and external customers and maintains customers’ trust by providing prompt, effective and quality service, takes continued interest in customers’ affairs.',
    Attachment: 'true',
    CurrentRate: '3/5',
    RequiredRate: '1/5',
    Gap: '2',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '8',
    TotalBudget: '$2200',
    Remarks:'',
  },
  {
    SN: 12,
    CompetencyType: 'Technical',
    Skills: 'Escalates suggestions on how to provide better services',
    Attachment: 'false',
    CurrentRate: '3/5',
    RequiredRate: '4/5',
    Gap: '-2',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '7',
    TotalBudget: '$1500',
    Remarks:'',
  },
  {
    SN: 13,
    CompetencyType: 'Technical',
    Skills: 'Understands internal and external customer requirements, customer needs and organisation’s service standards and takes initiative to provide value-added advice/ suggestions to address needs.',
    Attachment: 'true',
    CurrentRate: '3/5',
    RequiredRate: '3/5',
    Gap: '0',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '10',
    TotalBudget: '$3000',
    Remarks:'',
  },
  {
    SN: 14,
    CompetencyType: 'Technical',
    Skills: 'Escalates suggestions on how to provide better services',
    Attachment: 'false',
    CurrentRate: '3/5',
    RequiredRate: '4/5',
    Gap: '-1',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '7',
    TotalBudget: '$1500',
    Remarks:'',
  },
  {
    SN: 15,
    CompetencyType: 'Technical',
    Skills: 'Builds rapport with internal and external customers and maintains customers’ trust by providing prompt, effective and quality service, takes continued interest in customers’ affairs.',
    Attachment: 'false',
    CurrentRate: '3/5',
    RequiredRate: '1/5',
    Gap: '2',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '8',
    TotalBudget: '$2200',
    Remarks:'',
  },
  {
    SN: 16,
    CompetencyType: 'Technical',
    Skills: 'Escalates suggestions on how to provide better services',
    Attachment: 'true',
    CurrentRate: '3/5',
    RequiredRate: '4/5',
    Gap: '-2',
    Piority: '',
    CoursesInterested: 'My Training Plan',
    TotalHours: '7',
    TotalBudget: '$1500',
    Remarks:'',
  }
];
